apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd2
  name: httpd2
spec:
  containers:
  - image: httpd
    name: httpd2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
