apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mealie
  name: mealie
spec:
  containers:
  - image: nginx
    name: mealie
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
